export const COMPANY_LOADING = 'COMPANY_LOADING';
export const ERROR = 'ERROR';
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';
export const SET_COMPANY_IN_DETAILS = 'SET_COMPANY_IN_DETAILS';
