import { Metadata } from 'next';
import styles from './page.module.scss';

export const metadata: Metadata = {
  title: 'Сайт на тех обслуживании - Yeram',
  description: 'Generated by create next app',
};

const SiteIsInTechSupport = () => {
  return (
    <main className={styles.main}>
      <h3>Сайт на тех обслуживании</h3>
    </main>
  );
};

export default SiteIsInTechSupport;
