import { Metadata } from 'next';
import styles from './page.module.scss';

export const metadata: Metadata = {
  title: 'Политика конфиденциальности - Yeram',
  description: 'Generated by create next app',
};

const PrivacyPolicy = () => {
  return (
    <main className={styles.main}>
      <h3>Политика в отношении обработки персональных данных</h3>

      </div>
    </main>
  );
};

export default PrivacyPolicy;
